version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ordersystem
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ordersystem
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

  frontend:
    build: ../frontend/ecommerce-ui
    depends_on:
      - backend
    ports:
      - "3000:80"
